services:
  - type: web
    name: snackszone_shop
    env: docker
    plan: free
    repo: https://github.com/Mueid009/snackszone_shop_management
    branch: main
    dockerfilePath: Dockerfile
    releaseCommand: |
      php artisan config:clear
      php artisan migrate --force
      php artisan storage:link || true
      php artisan config:cache || true
