services:
  - type: web
    name: snackszone-web
    env: docker
    plan: free
    repo: https://github.com/Mueid009/snackszone_shop_management
    branch: main
    dockerfilePath: Dockerfile
    startCommand: php artisan serve --host 0.0.0.0 --port 10000