services:
  - type: web
    name: snackszone-web
    env: docker
    plan: free
    repo: https://github.com/Mueid009/snackszone_shop_management
    branch: main
    dockerfilePath: Dockerfile
    # run migrations & storage link before web service starts
    releaseCommand: |
      php artisan migrate --force
      php artisan storage:link
      php artisan config:cache
